### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.services.dynamodbv2.local.server.DynamoDBProxySer(short issue description)

### ISSUE THREAD

**Issue by VijayKumarSS** [aws/aws-sdk-java#2897]
### Describe the bug

after updating quarkus version to  2.15.1.Final  receiving above error 
	<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>DynamoDBLocal</artifactId>
			<version>1.17.2</version>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.apache.logging.log4j</groupId>
					<artifactId>log4j-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.logging.log4j</groupId>
					<artifactId>log4j-core</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

### Expected Behavior

it should execute all the tests

### Current Behavior

java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.services.dynamodbv2.local.server.DynamoDBProxyServer
	at com.bmw.registrations.vehicle.control.IVIDataServiceTest.setup(IVIDataServiceTest.java:123)

### Reproduction Steps

java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.services.dynamodbv2.local.server.DynamoDBProxyServer
	at com.bmw.registrations.vehicle.control.IVIDataServiceTest.setup(IVIDataServiceTest.java:123)

### Additional Information/Context
1.12.62

### AWS Java SDK version used

1.12.62

### JDK version used

11

### Operating System and version

windows

**Comment by VijayKumarSS** [comment]
<quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
		<quarkus.platform.version>2.10.1.Final</quarkus.platform.version>
		<surefire-plugin.version>3.0.0-M5</surefire-plugin.version>
		<lombok.version>1.18.22</lombok.version>


	<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>DynamoDBLocal</artifactId>
			<version>1.17.2</version>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.apache.logging.log4j</groupId>
					<artifactId>log4j-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.logging.log4j</groupId>
					<artifactId>log4j-core</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>2.17.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk-core</artifactId>
			<version>1.12.62</version>
		</dependency>
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk</artifactId>
			<version>1.12.62</version>
		</dependency>

**Comment by yasminetalby** [comment]
Hello @VijayKumarSS ,

DynamoDBLocal is not owned by the AWS Java SDK Team however I will be happy to relay your submission to the owner team and provide their update on this issue.

Did this behavior start happening solely after updating Quarkus version to 2.15.1. or was there any other change? 

Best,

Yasmine

**Comment by VijayKumarSS** [comment]
HI @yasminetalby ,

Yeah. after updating to Quarkus version to 2.15.1 this error we are receiving

**Comment by debora-ito** [comment]
@VijayKumarSS `NoClassDefFoundError` usually indicates a version mismatch of a dependency. 

If Quarkus is using DynamoDBLocal as a transient dependency and if you are also using DynamoDBLocal in your project, maven will resolve to one of those versions when you build your project. Executing the following command can help identify those version mismatches:
```
> mvn dependency:tree -Dverbose=true
```
This is not an issue with the SDK, it's a dependency version mismatch issue.
