### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.util.Base64

### ISSUE THREAD

**Issue by saurabhhv** [aws/aws-sdk-java#1428]
Can someone please suggest how to fix this error

2017-12-28 15:52:08,265 ERROR [stderr] (default task-38) java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.util.Base64
2017-12-28 15:52:08,266 ERROR [stderr] (default task-38)        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1730)

I am using "aws-java-sdk-bom" and tried to solve with version "1.11.109" and the latest "1.11.255" but the error do not get resolved.

Thanks in advance.

**Comment by kiiadi** [comment]
Definitely seems like a problem with dependency versions - that class hasn't been touched in a while as far as I know. Can you run `mvn dependency:tree -Dincludes=com.amazonaws:aws-java-sdk-core` to see where the `core` dependency is being pulled in from? There may be another project in your dependency chain that relies on an incompatible version of the SDK.

**Comment by saurabhhv** [comment]
Hi kiiadi, Thanks for your reply. please find the output of mvn dependency command provided by you
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building conductor-core 0.0.6
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ conductor-core ---
[INFO] com.asg:conductor-core:jar:0.0.6
[INFO] \- com.amazonaws:aws-java-sdk-core:jar:1.11.109:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.030 s
[INFO] Finished at: 2018-01-02T16:50:17-05:00
[INFO] Final Memory: 17M/222M
[INFO] ------------------------------------------------------------------------

**Comment by kiiadi** [comment]
Can you try `mvn dependency:tree -Dincludes=com.amazonaws` so that we can see all of the AWS SDK dependencies?

**Comment by saurabhhv** [comment]
Here is the output
>mvn dependency:tree -Dincludes=com.amazonaws
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building conductor-core 0.0.6
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ conductor-core ---
[INFO] com.asg:conductor-core:jar:0.0.6
[INFO] +- com.asg:persistent-data-store:jar:0.2.0:compile
[INFO] |  \- com.amazonaws:aws-java-sdk-dynamodb:jar:1.11.109:compile
[INFO] +- com.asg:core-app:jar:0.3.8:compile
[INFO] |  \- com.amazonaws:aws-java-sdk-cognitoidp:jar:1.11.109:compile
[INFO] +- com.amazonaws:aws-java-sdk-core:jar:1.11.109:compile
[INFO] +- com.amazonaws:aws-java-sdk-s3:jar:1.11.109:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-kms:jar:1.11.109:compile
[INFO] |  \- com.amazonaws:jmespath-java:jar:1.11.109:compile
[INFO] +- com.amazonaws:aws-java-sdk-lambda:jar:1.11.109:compile
[INFO] +- com.amazonaws:aws-lambda-java-core:jar:1.1.0:compile
[INFO] +- com.amazonaws:aws-lambda-java-events:jar:1.0.0:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-sns:jar:1.11.109:compile
[INFO] |  |  \- com.amazonaws:aws-java-sdk-sqs:jar:1.11.109:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-cognitoidentity:jar:1.11.109:compile
[INFO] |  \- com.amazonaws:aws-java-sdk-kinesis:jar:1.11.109:compile
[INFO] \- com.amazonaws:aws-lambda-java-log4j:jar:1.0.0:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.448 s
[INFO] Finished at: 2018-01-02T17:19:18-05:00
[INFO] Final Memory: 17M/223M
[INFO] ------------------------------------------------------------------------

**Comment by kiiadi** [comment]
@saurabhhv hrmm - any chance you can show me your pom.xml?

**Comment by saurabhhv** [comment]
<build>
		<sourceDirectory>src/main/java</sourceDirectory>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.5.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>2.3</version>
				<configuration>
					<createDependencyReducedPom>false</createDependencyReducedPom>
				</configuration>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
		<extensions>
			<extension>
				<groupId>org.kuali.maven.wagons</groupId>
				<artifactId>maven-s3-wagon</artifactId>
				<version>1.2.1</version>
			</extension>
		</extensions>
	</build>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.amazonaws</groupId>
				<artifactId>aws-java-sdk-bom</artifactId>
				<version>1.11.109</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<dependencies>
		
		<dependency>
			<groupId>com.asg</groupId>
			<artifactId>persistent-data-store</artifactId>
			<version>0.2.0</version>
		</dependency>
		<dependency>
			<groupId>com.asg</groupId>
			<artifactId>core-app</artifactId>
			<version>0.3.8</version>
		</dependency>

		
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk-core</artifactId>
		</dependency>
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk-s3</artifactId>
		</dependency>
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk-lambda</artifactId>
		</dependency>
		
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-lambda-java-core</artifactId>
			<version>1.1.0</version>
		</dependency>
		
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-lambda-java-events</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-lambda-java-log4j</artifactId>
			<version>1.0.0</version>
		</dependency>
		
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.11</version>
		</dependency>
		
		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
			<version>2.6</version>
		</dependency>

		
		<dependency>
			<groupId>javax.mail</groupId>
			<artifactId>mail</artifactId>
			<version>1.4</version>
		</dependency>
		
		<dependency>
			<groupId>javax.activation</groupId>
			<artifactId>activation</artifactId>
			<version>1.1.1</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.ws.security</groupId>
			<artifactId>wss4j</artifactId>
			<version>1.5.12</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.axis</groupId>
			<artifactId>axis</artifactId>
			<version>1.4</version>
		</dependency>
		
		<dependency>
			<groupId>commons-discovery</groupId>
			<artifactId>commons-discovery</artifactId>
			<version>0.2</version>
		</dependency>
		
		<dependency>
			<groupId>javax.xml</groupId>
			<artifactId>jaxrpc-api</artifactId>
			<version>1.1</version>
		</dependency>
		
		<dependency>
			<groupId>wsdl4j</groupId>
			<artifactId>wsdl4j</artifactId>
			<version>1.6.2</version>
		</dependency>
		
		<dependency>
		    <groupId>com.thoughtworks.xstream</groupId>
		    <artifactId>xstream</artifactId>
		    <version>1.4.10</version>
		</dependency>
		
		
	</dependencies>

**Comment by slnowak** [comment]
@kiiadi 
I've just encountered the same error when trying to use 1.8.10 version of amazon-kinesis-client on jdk9. It works fine on jdk 1.8.

Here's the result of dependency:tree:
```
[INFO] \- com.amazonaws:amazon-kinesis-client:jar:1.8.10:compile
[INFO]    +- com.amazonaws:aws-java-sdk-dynamodb:jar:1.11.271:compile
[INFO]    |  +- com.amazonaws:aws-java-sdk-s3:jar:1.11.271:compile
[INFO]    |  |  \- com.amazonaws:aws-java-sdk-kms:jar:1.11.271:compile
[INFO]    |  +- com.amazonaws:aws-java-sdk-core:jar:1.11.271:compile
[INFO]    |  \- com.amazonaws:jmespath-java:jar:1.11.271:compile
[INFO]    +- com.amazonaws:aws-java-sdk-kinesis:jar:1.11.271:compile
[INFO]    \- com.amazonaws:aws-java-sdk-cloudwatch:jar:1.11.271:compile
```

**Comment by ollierob** [comment]
Regardless of the cause this is quite bad, as (at least in my application) it seems to cause ``Upload``s to get stuck at 0% and not reported anywhere as having failed - spent all morning today digging into my executors to figure out what's going wrong. 

Java 8 stacktrace where the only declared dependency I have is `aws-java-sdk-s3:1.11.291`:
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.util.Base64
        at com.amazonaws.util.Md5Utils.md5AsBase64(Md5Utils.java:104)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1648)
        at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:133)
        at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:125)
        at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:143)
        at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:48)
        at java.util.concurrent.FutureTask.run(Unknown Source)
```

**Comment by ollierob** [comment]
Seems to be a JAXB initialization issue:
```
Caused by: java.lang.NoClassDefFoundError: com/sun/xml/bind/v2/model/annotation/AnnotationReader
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at javax.xml.bind.ContextFinder.newInstance(Unknown Source)
        at javax.xml.bind.ContextFinder.newInstance(Unknown Source)
        at javax.xml.bind.ContextFinder.find(Unknown Source)
        at javax.xml.bind.JAXBContext.newInstance(Unknown Source)
        at javax.xml.bind.JAXBContext.newInstance(Unknown Source)
        at com.amazonaws.util.Base64.<clinit>(Base64.java:44)
        ...
```
I think https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/util/Base64.java#L51 should also catch all `Throwable`.

**Comment by dagnir** [comment]
I suspect the issue is Java 9 related as @slnowak suggested since the JAX APIs were removed as part of the default classpath in Java 9. If you're on Java 9, it looks like one solution is to add the `java.se.ee` module: https://docs.oracle.com/javase/9/docs/api/java.se.ee-summary.html

I think @ollierob's suggestion to catch `Throwable` instead should be fine. I'll go ahead and make the change upstream

**Comment by ollierob** [comment]
Not sure it's Java 9 related as we are using Java 8, but a fix/workaround is to make sure the below dependency has compile-time scope in Maven (we had it `provided`, I'm not sure how it's declared in the AWS SDK):
```
<dependency>
  <groupId>com.sun.xml.bind</groupId>
  <artifactId>jaxb-core</artifactId>
</dependency>
```

**Comment by dagnir** [comment]
@ollierob  I see. Would you mind sharing what JDK and version you're using? It's weird that @slnowak got it to work by switching back to 1.8 but didn't work in your case.

**Comment by shorea** [comment]
We've fixed this to fallback to the SDK Base64 implementation if Java EE is not available. It should now work in Java 9 with the latest version of the SDK.

**Comment by yegor256** [comment]
I my case it was a conflict between two versions of `jaxb-core` in classpath. [Removing](https://github.com/yegor256/rultor/commit/6857f0247fcdea40be2bc73d1bec23ebf9901dd5) one of them solved the problem.
