### ISSUE TITLE
Question on AWS java sdk

### ISSUE THREAD

**Issue by bhadradeka** [aws/aws-sdk-java#850]
I updated to the 1.11.34 from 1.9.22, i am getting an exception

"NoClassDefFoundError:org/apache/http/conn/socket/ConnectionSocketFactory"

1) Does the new version of sdk work with httpclient-4.2.1 and httpcore-4.2.1 or is it a strict need to update to 4.5.2 ?

2)I replace the httpclient/core jars to latest then i am getting an 
NoSuchMethodError:com.fasterxml.jackson.databind.ObjectMapper.enable([Lcom/fasterxml/jackson/core/JsonParser$Feature;)Lcom/fasterxml/jackson/databind/ObjectMapper

My jackson librariers are 2.3.3 do I need to update them as well, to get it working

I have a jetty server version which is dependent on the jackson libraries ....

**Comment by shorea** [comment]
The dependencies listed in our POM are minimum requirements so you'll need to update Apache HTTP client to 4.5..2 and Jackson to 2.6.6.
